### ISSUE TITLE
Preserve quotes

### ISSUE THREAD

**Issue by dtolnay** [nathanwhit/minimal-yaml#3]
minimal-yaml appears to discard quotes. Both of the following

```
k: 1
k: "1"
```

are parsed as `Entry { key: Scalar("k"), value: Scalar("1") }`. This is bad because downstream code would need to be able to tell the difference between the two and treat the first as a number and the second as a string.

**Comment by nathanwhit** [comment]
I was split between discarding quotes in order to adhere to the YAML specification, and preserving them as you suggest. Overall I agree preserving quotes does add more value than adhering to the specification (which the library already diverges from), so I'll go ahead and make that change.

**Comment by dtolnay** [comment]
I'm not sure why you see this as diverging from the specification. Double quoted strings are scalars according to https://yaml.org/spec/1.2/spec.html#style/flow/double-quoted. They are represented by *c-double-quoted(n,c)* in that document.

**Comment by nathanwhit** [comment]
Right. I suppose I interpreted the intent of the Scalar enum variant as containing the _content_ of the scalar instead of the literal scalar, and since the specification considers the outer quotes as indicator characters they wouldn't be considered content. So with that in mind, I thought you were proposing to consider the quotes as part of the scalar's content, which would diverge from the specification.
